### ISSUE TITLE
Action Log not working properly with Oauth

### ISSUE THREAD

**Issue by EvilExecutor** [SychO9/flarum-action-log#2] opened 2020-12-05 15:06 UTC
When Action Log is enabled with FoF Oauth, when users try to signup using Discord, or any other Social media account the user gets an error telling to reload the page. Although this happens the user is Signed up, but not recorded in the Action Log in Admin panel. I will attach some screenshots below. And once again great work Sycho!

![bandicam 2020-12-05 20-51-50-657](https://user-images.githubusercontent.com/69867743/101246850-c608dd80-373b-11eb-8f53-781a243f8364.jpg)
![error](https://user-images.githubusercontent.com/69867743/101246883-f9e40300-373b-11eb-8aef-489621345a72.PNG)

**Comment by SychO9** [comment] 2020-12-05 15:13
Interesting, I'll try using fof/oath with it and see, but at a first glance I'm not sure if the problem is with this extension itself.

**Comment by EvilExecutor** [comment] 2020-12-05 15:29
At least it happens only when the extension is enabled 😅

**Comment by SychO9** [comment] 2020-12-12 16:39
Fixed in https://github.com/SychO9/flarum-action-log/commit/f33f0cb3be57573c449e8499cbad288709a648b8

**Closed as completed by SychO9** 2020-12-12 16:39 UTC
